---
openapi: 3.0.1
info:
  title: FLETX API
  version: v1
  description: API documentation for FLETX application
paths:
  "/api/v1/examples":
    get:
      summary: Lista todos los ejemplos
      tags:
      - Examples
      responses:
        '200':
          description: lista de ejemplos encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    created_at:
                      type: string
                      format: datetime
                    updated_at:
                      type: string
                      format: datetime
                  required:
                  - id
                  - name
    post:
      summary: Crea un ejemplo
      tags:
      - Examples
      parameters: []
      responses:
        '201':
          description: ejemplo creado
        '422':
          description: entidad no procesable
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
  "/api/v1/examples/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Obtiene un ejemplo
      tags:
      - Examples
      responses:
        '200':
          description: ejemplo encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                required:
                - id
                - name
        '404':
          description: ejemplo no encontrado
  "/api/v1/magic_auths":
    post:
      summary: Crea un token de autenticación
      tags:
      - Magic Links
      parameters: []
      responses:
        '200':
          description: token de autenticación creado
          headers:
            X-JWT-Token:
              schema:
                type: string
              description: JWT token para autenticación
            Authorization:
              schema:
                type: string
              description: Bearer token para autenticación
            Set-Cookie:
              schema:
                type: string
              description: Cookie con el JWT token
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/auth_success_response"
        '401':
          description: token de autenticación no válido
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                magic_link:
                  type: object
                  properties:
                    token:
                      type: string
                  required:
                  - token
              required:
              - magic_link
  "/api/v1/magic_links":
    post:
      summary: Crea un magic link
      tags:
      - Magic Links
      parameters: []
      responses:
        '200':
          description: magic link creado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/magic_link_success_response"
        '422':
          description: entidad no procesable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
              required:
              - email
components:
  schemas:
    magic_link_success_response:
      type: object
      properties:
        magic_link:
          type: object
          properties:
            message:
              type: string
          required:
          - message
      required:
      - magic_link
    auth_success_response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiJ9...
      required:
      - success
      - token
    error_response:
      type: object
      properties:
        error:
          type: string
          example: Token expirado
      required:
      - error
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookie_auth:
      type: apiKey
      name: jwt
      in: cookie
  headers:
    X-JWT-Token:
      description: JWT token for authentication
      schema:
        type: string
    Set-Cookie:
      description: Cookie containing the JWT token
      schema:
        type: string
servers:
- url: http://localhost:3000
  description: Development server
