---
openapi: 3.0.1
info:
  title: FLETX API
  version: v1
  description: API documentation for FLETX application
paths:
  "/api/v1/examples":
    get:
      summary: Lista todos los ejemplos
      tags:
      - Examples
      responses:
        '200':
          description: lista de ejemplos encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    created_at:
                      type: string
                      format: datetime
                    updated_at:
                      type: string
                      format: datetime
                  required:
                  - id
                  - name
    post:
      summary: Crea un ejemplo
      tags:
      - Examples
      parameters: []
      responses:
        '201':
          description: ejemplo creado
        '422':
          description: entidad no procesable
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
  "/api/v1/examples/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Obtiene un ejemplo
      tags:
      - Examples
      responses:
        '200':
          description: ejemplo encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                required:
                - id
                - name
        '404':
          description: ejemplo no encontrado
  "/api/v1/magic_links":
    post:
      summary: Crea un magic link
      tags:
      - Magic Links
      parameters: []
      responses:
        '200':
          description: magic link creado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/magic_link_success_response"
        '422':
          description: entidad no procesable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
              required:
              - email
components:
  schemas:
    magic_link_success_response:
      type: object
      properties:
        magic_link:
          type: object
          properties:
            message:
              type: string
          required:
          - message
      required:
      - magic_link
    error_response:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
- url: http://localhost:3000
  description: Development server
