---
openapi: 3.0.1
info:
  title: FLETX API
  version: v1
  description: API documentation for FLETX application
paths:
  "/api/v1/companies":
    post:
      summary: Crea una nueva empresa
      tags:
      - Empresas
      description: Esta respuesta ocurre cuando los datos proporcionados no son válidos
        para crear una empresa.
      security:
      - bearer_auth: []
      - api_key_auth: []
      parameters: []
      responses:
        '200':
          description: empresa creada
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '403':
          description: sin autorización para esta acción
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '404':
          description: ciudad no encontrada
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '422':
          description: entidad no procesable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/company_request"
    get:
      summary: Obtiene listado de empresas
      tags:
      - Empresas
      description: Esta respuesta ocurre cuando no se proporciona un token JWT válido
        o cuando éste ha expirado.
      security:
      - bearer_auth: []
      - api_key_auth: []
      responses:
        '200':
          description: listado de empresas
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/company"
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
  "/api/v1/companies/{id}":
    parameters:
    - name: id
      in: path
      description: ID de la empresa a consultar
      required: true
      schema:
        type: integer
    get:
      summary: Obtiene detalles de una empresa específica
      tags:
      - Empresas
      description: Esta respuesta ocurre cuando no existe una empresa con el ID proporcionado.
      security:
      - bearer_auth: []
      - api_key_auth: []
      responses:
        '200':
          description: detalle de empresa
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '403':
          description: sin autorización para esta acción
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '404':
          description: empresa no encontrada
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
    put:
      summary: Actualiza una empresa existente
      tags:
      - Empresas
      description: Esta respuesta ocurre cuando los datos proporcionados no son válidos
        para actualizar la empresa.
      security:
      - bearer_auth: []
      - api_key_auth: []
      parameters:
      - name: id
        in: path
        description: ID de la empresa a actualizar
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: empresa actualizada correctamente
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '403':
          description: sin autorización para esta acción
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '404':
          description: empresa o ciudad no encontrada
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '422':
          description: entidad no procesable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/company_request"
  "/api/v1/departments":
    get:
      summary: Obtiene listado de departamentos
      tags:
      - Departamentos
      description: Este endpoint devuelve el listado de todos los departamentos con
        sus ciudades asociadas.
      responses:
        '200':
          description: listado de departamentos
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/departments_response"
  "/api/v1/magic_auths":
    post:
      summary: Crea una sesión autenticada usando un token de Magic Link
      tags:
      - Autenticación
      description: |-
        Esta respuesta ocurre cuando el token proporcionado no es válido,
                ha expirado o ya ha sido utilizado.
      parameters: []
      responses:
        '200':
          description: token de autenticación creado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/auth_success_response"
        '401':
          description: token de autenticación no válido
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                magic_link:
                  type: object
                  properties:
                    token:
                      type: string
                      description: Token de un solo uso generado previamente mediante
                        el endpoint de magic_links
                  required:
                  - token
              required:
              - magic_link
  "/api/v1/magic_links":
    post:
      summary: Crea un magic link
      tags:
      - Magic Links
      parameters: []
      responses:
        '200':
          description: magic link creado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/magic_link_success_response"
        '422':
          description: entidad no procesable
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/api/v1/me":
    get:
      summary: Obtiene información del usuario autenticado
      tags:
      - Perfil
      description: Esta respuesta ocurre cuando no se proporciona un token JWT válido
        o cuando éste ha expirado.
      security:
      - bearer_auth: []
      - api_key_auth: []
      responses:
        '200':
          description: información del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: usuario@example.com
                required:
                - email
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
  "/api/v1/users":
    get:
      summary: Obtiene listado de usuarios
      tags:
      - Usuarios
      description: Esta respuesta ocurre cuando el usuario no tiene los permisos necesarios
        para listar usuarios.
      security:
      - bearer_auth: []
      - api_key_auth: []
      responses:
        '200':
          description: listado de usuarios
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/users_response"
        '401':
          description: no autorizado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
        '403':
          description: sin autorización para esta acción
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error_response"
components:
  schemas:
    magic_link_success_response:
      type: object
      properties:
        magic_link:
          type: object
          properties:
            message:
              type: string
              example: Se ha enviado un enlace mágico a tu correo electrónico
          required:
          - message
      required:
      - magic_link
      description: Respuesta enviada cuando se solicita un magic link
    auth_success_response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiJ9...
      required:
      - success
      - token
      description: Respuesta enviada cuando la autenticación es exitosa. El token
        JWT se envía en el cuerpo de la respuesta.
    error_response:
      type: object
      oneOf:
      - properties:
          error:
            type: string
            example: Token expirado
        required:
        - error
      - properties:
          errors:
            type: array
            items:
              type: string
            example:
            - Email is invalid
        required:
        - errors
      - properties:
          errors:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
            example:
              name:
              - can't be blank
        required:
        - errors
      description: Respuesta enviada cuando ocurre un error de autenticación o validación
    city:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Medellín
      required:
      - id
      - name
      description: Información básica de una ciudad
    department:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Antioquia
        cities:
          type: array
          items:
            "$ref": "#/components/schemas/city"
      required:
      - id
      - name
      - cities
      description: Información de un departamento con sus ciudades asociadas
    departments_response:
      type: array
      items:
        "$ref": "#/components/schemas/department"
      description: Lista de departamentos con sus ciudades asociadas
    role:
      type: object
      properties:
        id:
          type: integer
          example: 1
        code:
          type: string
          example: admin
        description:
          type: string
          example: Administrador
      required:
      - id
      - code
      - description
      description: Información de un rol de usuario
    user:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: usuario@example.com
        name:
          type: string
          example: Juan
        lastName:
          type: string
          example: Pérez
        workPosition:
          type: string
          example: Gerente
        phoneNumber:
          type: string
          example: '3001234567'
        salary:
          type: number
          format: float
          example: 5000000.0
        role:
          "$ref": "#/components/schemas/role"
        company:
          type: object
          nullable: true
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: FLETX Inc.
          required:
          - id
          - name
      required:
      - id
      - email
      - role
      description: Información de un usuario
    users_response:
      type: array
      items:
        "$ref": "#/components/schemas/user"
      description: Lista de usuarios
    company:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: FLETX Inc.
        category:
          type: string
          example: Transporte
        address:
          type: string
          example: Calle Principal 123
        phone_number:
          type: string
          example: '3001234567'
        assets:
          type: string
          example: '100000.0'
        liabilities:
          type: string
          example: '50000.0'
        department:
          type: object
          nullable: true
          properties:
            id:
              type: integer
            name:
              type: string
        city:
          type: object
          nullable: true
          properties:
            id:
              type: integer
            name:
              type: string
      required:
      - id
      - name
      - category
      - address
      - phone_number
      - assets
      - liabilities
      description: Información completa de una empresa
    company_request:
      type: object
      properties:
        company:
          type: object
          properties:
            name:
              type: string
              example: FLETX Inc.
            category:
              type: string
              example: Transporte
            address:
              type: string
              example: Calle Principal 123
            phone_number:
              type: string
              example: '3001234567'
            assets:
              type: number
              format: float
              example: 100000.0
            liabilities:
              type: number
              format: float
              example: 50000.0
            city_id:
              type: integer
              example: 1
          required:
          - name
          - category
          - address
          - phone_number
          - assets
          - liabilities
          - city_id
      required:
      - company
      description: Solicitud para crear una nueva empresa
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key_auth:
      type: apiKey
      name: X-JWT-Token
      in: header
  headers:
    X-JWT-Token:
      description: JWT token for authentication
      schema:
        type: string
servers:
- url: http://localhost:3000
  description: Development server
