name: Backend Checks

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests & Linting
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: file:./backend/.ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Setup database
        working-directory: backend
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/backend_test
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec tests
        working-directory: backend
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/backend_test
        run: bundle exec rspec

      - name: Run Rubocop
        working-directory: backend
        run: bundle exec rubocop

      - name: Run Brakeman security analysis
        working-directory: backend
        run: bundle exec brakeman
