name: Backend Checks

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests & Linting
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: backend

      - name: Cache Ruby bundle
        uses: actions/cache@v4
        with:
          path: ~/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config set --local path '~/vendor/bundle'
          bundle install
        working-directory: backend

      - name: Prepare database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
        working-directory: backend

      - name: Run RSpec tests
        run: bundle exec rspec
        working-directory: backend

      - name: Run Rubocop
        run: bundle exec rubocop
        working-directory: backend

      - name: Run Brakeman security analysis
        run: bundle exec brakeman
        working-directory: backend
